import jenkins.*;
import jenkins.model.*;

def cloneGitRepo() {
  stage('Cloning Git') {           
    checkout([
      $class: 'GitSCM', 
      branches: [[name: '*/master']], 
      doGenerateSubmoduleConfigurations: false, 
      extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'code_directory']], 
      submoduleCfg: [], 
      userRemoteConfigs: [[credentialsId: '', url: 'https://github.com/demask/repo-free.git']]])                 
  }

  stage('Cloning Terraform Git') {           
    checkout([
      $class: 'GitSCM', 
      branches: [[name: '*/master']], 
      doGenerateSubmoduleConfigurations: false, 
      extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'terraform_directory']], 
      submoduleCfg: [], 
      userRemoteConfigs: [[credentialsId: '', url: 'https://github.com/demask/aws_codebuild_codedeploy_nodeJs_demo_terraform.git']]])                 
  } 
}

def runTerraform(dockerImageTag) {
  stage('Terraform Init') {     
    sh 'terraform init -no-color'
  }
                
  stage('Terraform Apply') {     
    sh ("""terraform apply \
    -var=\"docker_image_tag=${dockerImageTag}\" \
    -auto-approve -no-color""")
  }
}

def createTaskDefinitions() {
  newDockerImageMap.each{
    if(it.key == 'other-repo-job') {
      dir("${env.WORKSPACE}/terraform_directory/dev/task-definitions/other-repo-job"){
        runTerraform(it.value)     
      } 
    } 
  }   
}

def buildDockerImage(IMAGE_TAG, IMAGE_REPO_NAME, DOCKERFILE, AWS_ACCOUNT_ID, AWS_DEFAULT_REGION, newDockerImageMap) {
  def REPOSITORY_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}"

  stage('Building image') {
    dockerImage = docker.build("${IMAGE_REPO_NAME}:${IMAGE_TAG}", "-f ${DOCKERFILE} .")                         
  }
   
  stage('Push image to ECR') {         
    sh "docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}:${IMAGE_TAG}"
    sh "docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}:${IMAGE_TAG}"                            
  }

  newDockerImageMap[IMAGE_REPO_NAME] = IMAGE_TAG
}

def createAndPushDockerImages(currentBuild, AWS_ACCOUNT_ID, AWS_DEFAULT_REGION) {
  def newDockerImageMap = [:]
  dir("${env.WORKSPACE}/code_directory"){  
    def IMAGE_TAG = sh (script: 'git rev-parse --short HEAD',returnStdout: true).trim()
    def DOCKERFILE = 'Dockerfile'
    def IMAGE_REPO_NAME="other-repo-job"
    buildDockerImage(IMAGE_TAG, IMAGE_REPO_NAME, DOCKERFILE, AWS_ACCOUNT_ID, AWS_DEFAULT_REGION, newDockerImageMap)
  }

  return newDockerImageMap
}

node {
  def AWS_ACCOUNT_ID="246005639140"
  def AWS_DEFAULT_REGION="eu-central-1" 

  stage('Clean workspace') {      
    cleanWs()           
  }

  stage('Logging into AWS ECR') {      
    sh "aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"           
  }
        
  cloneGitRepo()
  def newDockerImageMap = createAndPushDockerImages(currentBuild, jobsByProjectPath, AWS_ACCOUNT_ID, AWS_DEFAULT_REGION)
  createTaskDefinitions(newDockerImageMap)
}